language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
script:
- npm run build
- npm run coveralls
before_deploy:
- gcloud --quiet version
- openssl aes-256-cbc -K $encrypted_07629293dfb8_key -iv $encrypted_07629293dfb8_iv -in gcloud-service-key.json.enc -out gcloud-service-key.json -d
- gcloud auth activate-service-account --key-file gcloud-service-key.json
- gcloud config set project brown-critical-review
deploy:
- provider: script
  script:
  - cp build/* . && gcloud beta --quiet functions deploy api --trigger-http --region="us-east1" --runtime="nodejs8"
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script:
  - cp build/* . && gcloud beta --quiet functions deploy "api-develop" --trigger-http --region="us-east1" --runtime="nodejs8"
  skip_cleanup: true
  on:
    branch: develop